// positions-primera-nacional-2025.ts
const ZONE_A_POSITIONS = [
  {
    position: 1,
    team: "Dep. Madryn" as const,
    pts: 60,
    pj: 34,
    pg: 16,
    pe: 12,
    pp: 6,
    gf: 45,
    gc: 28,
    dg: 17,
    imageSrc: "images/team/bbjbh/4",
  },
  {
    position: 2,
    team: "Atlanta" as const,
    pts: 55,
    pj: 34,
    pg: 14,
    pe: 13,
    pp: 7,
    gf: 31,
    gc: 28,
    dg: 3,
    imageSrc: "images/team/hbae/4",
  },
  {
    position: 3,
    team: "Tristán Suárez" as const,
    pts: 52,
    pj: 34,
    pg: 12,
    pe: 16,
    pp: 6,
    gf: 33,
    gc: 23,
    dg: 10,
    imageSrc: "images/team/hbbd/4",
  },
  {
    position: 4,
    team: "Gimnasia y Tiro (S)" as const,
    pts: 51,
    pj: 34,
    pg: 13,
    pe: 12,
    pp: 9,
    gf: 34,
    gc: 23,
    dg: 11,
    imageSrc: "images/team/jchi/4",
  },
  {
    position: 5,
    team: "San Miguel" as const,
    pts: 50,
    pj: 34,
    pg: 12,
    pe: 14,
    pp: 8,
    gf: 32,
    gc: 28,
    dg: 4,
    imageSrc: "images/team/bbiji/4",
  },
  {
    position: 6,
    team: "San Martín (T)" as const,
    pts: 49,
    pj: 34,
    pg: 12,
    pe: 13,
    pp: 9,
    gf: 32,
    gc: 29,
    dg: 3,
    imageSrc: "images/team/hchb/4",
  },
  {
    position: 7,
    team: "Deportivo Maipú" as const,
    pts: 48,
    pj: 34,
    pg: 12,
    pe: 12,
    pp: 10,
    gf: 34,
    gc: 30,
    dg: 4,
    imageSrc: "images/team/jcid/4",
  },
  {
    position: 8,
    team: "Patronato" as const,
    pts: 48,
    pj: 34,
    pg: 12,
    pe: 12,
    pp: 10,
    gf: 31,
    gc: 28,
    dg: 3,
    imageSrc: "images/team/iche/4",
  },
];

const ZONE_B_POSITIONS = [
  {
    position: 1,
    team: "Gimnasia y Esgrima (M)" as const,
    pts: 63,
    pj: 34,
    pg: 17,
    pe: 12,
    pp: 5,
    gf: 35,
    gc: 18,
    dg: 17,
    imageSrc: "images/team/bbjbf/4",
  },
  {
    position: 2,
    team: "Estudiantes (RC)" as const,
    pts: 60,
    pj: 34,
    pg: 16,
    pe: 12,
    pp: 6,
    gf: 35,
    gc: 22,
    dg: 13,
    imageSrc: "images/team/bheaf/4",
  },
  {
    position: 3,
    team: "Estudiantes (BA)" as const,
    pts: 59,
    pj: 34,
    pg: 17,
    pe: 8,
    pp: 9,
    gf: 41,
    gc: 22,
    dg: 19,
    imageSrc: "images/team/hbbg/4",
  },
  {
    position: 4,
    team: "Deportivo Morón" as const,
    pts: 58,
    pj: 34,
    pg: 15,
    pe: 13,
    pp: 6,
    gf: 36,
    gc: 19,
    dg: 17,
    imageSrc: "images/team/hbba/4",
  },
  {
    position: 5,
    team: "Gimnasia y Esgrima (J)" as const,
    pts: 57,
    pj: 34,
    pg: 15,
    pe: 12,
    pp: 7,
    gf: 36,
    gc: 20,
    dg: 16,
    imageSrc: "images/team/iib/4",
  },
  {
    position: 6,
    team: "Temperley" as const,
    pts: 55,
    pj: 34,
    pg: 14,
    pe: 13,
    pp: 7,
    gf: 30,
    gc: 22,
    dg: 8,
    imageSrc: "images/team/hbac/4",
  },
  {
    position: 7,
    team: "Agropecuario" as const,
    pts: 54,
    pj: 34,
    pg: 15,
    pe: 9,
    pp: 10,
    gf: 43,
    gc: 34,
    dg: 9,
    imageSrc: "images/team/bbjce/4",
  },
  {
    position: 8,
    team: "Chaco For Ever" as const,
    pts: 53,
    pj: 34,
    pg: 15,
    pe: 8,
    pp: 11,
    gf: 34,
    gc: 26,
    dg: 8,
    imageSrc: "images/team/bdiha/4",
  },
];

export const positions = {
  zoneA: ZONE_A_POSITIONS,
  zoneB: ZONE_B_POSITIONS,
};

export type TeamPosition = (
  | typeof ZONE_A_POSITIONS
  | typeof ZONE_B_POSITIONS
)[number];
export type TeamName = TeamPosition["team"];
