const ZONE_A_POSITIONS = [
  {
    position: 1,
    team: "San Martin (T)" as const,
    pts: 81,
    pj: 38,
    pg: 24,
    pe: 9,
    pp: 5,
    gf: 43,
    gc: 18,
    dg: 25,
    imageSrc: "images/18/37.png",
  },
  {
    position: 2,
    team: "San Martin (SJ)" as const,
    pts: 70,
    pj: 38,
    pg: 19,
    pe: 13,
    pp: 6,
    gf: 40,
    gc: 21,
    dg: 19,
    imageSrc: "images/18/36.png",
  },
  {
    position: 3,
    team: "Quilmes" as const,
    pts: 60,
    pj: 38,
    pg: 17,
    pe: 12,
    pp: 9,
    gf: 41,
    gc: 24,
    dg: 17,
    imageSrc: "images/18/16.png",
  },
  {
    position: 4,
    team: "All Boys" as const,
    pts: 58,
    pj: 38,
    pg: 15,
    pe: 13,
    pp: 10,
    gf: 34,
    gc: 24,
    dg: 10,
    imageSrc: "images/18/2.png",
  },
  {
    position: 5,
    team: "Gimnasia (J)" as const,
    pts: 58,
    pj: 38,
    pg: 17,
    pe: 7,
    pp: 14,
    gf: 32,
    gc: 27,
    dg: 5,
    imageSrc: "images/18/31.png",
  },
  {
    position: 6,
    team: "Estudiantes (BA)" as const,
    pts: 56,
    pj: 38,
    pg: 14,
    pe: 14,
    pp: 10,
    gf: 34,
    gc: 32,
    dg: 2,
    imageSrc: "images/18/64.png",
  },
  {
    position: 7,
    team: "Racing (C)" as const,
    pts: 53,
    pj: 38,
    pg: 14,
    pe: 11,
    pp: 13,
    gf: 37,
    gc: 36,
    dg: 1,
    imageSrc: "images/18/79.png",
  },
  {
    position: 8,
    team: "San Miguel" as const,
    pts: 53,
    pj: 38,
    pg: 13,
    pe: 14,
    pp: 11,
    gf: 34,
    gc: 33,
    dg: 1,
    imageSrc: "images/18/101.png",
  },
];

const ZONE_B_POSITIONS = [
  {
    position: 1,
    team: "Aldosivi" as const,
    pts: 64,
    pj: 38,
    pg: 17,
    pe: 13,
    pp: 8,
    gf: 41,
    gc: 24,
    dg: 17,
    imageSrc: "images/18/22.png",
  },
  {
    position: 2,
    team: "Dep. Madryn" as const,
    pts: 64,
    pj: 38,
    pg: 17,
    pe: 13,
    pp: 8,
    gf: 35,
    gc: 20,
    dg: 15,
    imageSrc: "images/18/178.png",
  },
  {
    position: 3,
    team: "Nueva Chicago" as const,
    pts: 64,
    pj: 38,
    pg: 18,
    pe: 10,
    pp: 10,
    gf: 39,
    gc: 25,
    dg: 14,
    imageSrc: "images/18/42.png",
  },
  {
    position: 4,
    team: "Gimnasia (M)" as const,
    pts: 63,
    pj: 38,
    pg: 17,
    pe: 12,
    pp: 9,
    gf: 44,
    gc: 33,
    dg: 11,
    imageSrc: "images/18/156.png",
  },
  {
    position: 5,
    team: "San Telmo" as const,
    pts: 62,
    pj: 38,
    pg: 18,
    pe: 11,
    pp: 9,
    gf: 49,
    gc: 25,
    dg: 24,
    imageSrc: "images/18/91.png",
  },
  {
    position: 6,
    team: "Colon" as const,
    pts: 58,
    pj: 38,
    pg: 16,
    pe: 10,
    pp: 12,
    gf: 40,
    gc: 26,
    dg: 14,
    imageSrc: "images/18/7.png",
  },
  {
    position: 7,
    team: "Def. de Belgrano" as const,
    pts: 58,
    pj: 38,
    pg: 15,
    pe: 13,
    pp: 10,
    gf: 38,
    gc: 24,
    dg: 14,
    imageSrc: "images/18/43.png",
  },
  {
    position: 8,
    team: "Gimnasia (S)" as const,
    pts: 58,
    pj: 38,
    pg: 14,
    pe: 16,
    pp: 8,
    gf: 27,
    gc: 22,
    dg: 5,
    imageSrc: "images/18/53.png",
  },
];

export const positions = {
  zoneA: ZONE_A_POSITIONS,
  zoneB: ZONE_B_POSITIONS,
};

export type TeamPosition = (
  | typeof ZONE_A_POSITIONS
  | typeof ZONE_B_POSITIONS
)[number];
export type TeamName = TeamPosition["team"];
